//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Stellar.RPC
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.1.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [ProtoBuf.ProtoContract] public partial class GetLedgerEntriesResult
    {
        /// <summary>
        /// The sequence number of the latest ledger known to Stellar RPC at the time it handled the request.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("latestLedger")]
        [ProtoBuf.ProtoMember(1)] public long  LatestLedger { get; set; }

        /// <summary>
        /// Array of objects containing all found ledger entries
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("entries")]
        [ProtoBuf.ProtoMember(2)] public System.Collections.Generic.List<Entries>  Entries { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Object containing information about an existing ledger entry.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.1.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [ProtoBuf.ProtoContract] public partial class Entries
    {
        /// <summary>
        /// The key of the ledger entry (serialized in a base64 string).
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("key")]
        [ProtoBuf.ProtoMember(1)] public string  Key { get; set; }

        /// <summary>
        /// The current value of the given ledger entry (serialized in a base64 string).
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("xdr")]
        [ProtoBuf.ProtoMember(2)] public string  Xdr { get; set; }

        /// <summary>
        /// The ledger sequence number of the last time this entry was updated.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("lastModifiedLedgerSeq")]
        [ProtoBuf.ProtoMember(3)] public long  LastModifiedLedgerSeq { get; set; }

        /// <summary>
        /// Sequence number of the ledger.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("liveUntilLedgerSeq")]
        [ProtoBuf.ProtoMember(4)] public long  LiveUntilLedgerSeq { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }
}