//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Stellar.RPC
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.1.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetVersionInfoResult
    {
        /// <summary>
        /// The version of the RPC server.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Version { get; set; }

        /// <summary>
        /// The commit hash of the RPC server.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("commit_hash", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Commit_hash { get; set; }

        /// <summary>
        /// The build timestamp of the RPC server.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("build_time_stamp", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Build_time_stamp { get; set; }

        /// <summary>
        /// The version of the Captive Core.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("captive_core_version", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Captive_core_version { get; set; }

        /// <summary>
        /// The protocol version.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("protocol_version", Required = Newtonsoft.Json.Required.Always)]
        public int Protocol_version { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

        public string ToJson()
        {

            return Newtonsoft.Json.JsonConvert.SerializeObject(this, new Newtonsoft.Json.JsonSerializerSettings());

        }
        public static GetVersionInfoResult FromJson(string data)
        {

            return Newtonsoft.Json.JsonConvert.DeserializeObject<GetVersionInfoResult>(data, new Newtonsoft.Json.JsonSerializerSettings());

        }

    }
}