[package]
name = "rust_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["full"] }
libloading = "0.8"
tower = "0.4"


[build-dependencies]
tonic-build = "0.10"
