name: Build and Release SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SDK Version (e.g., 1.0.0)'
        required: true
      update_specs:
        description: 'Update OpenRPC and XDR specifications'
        type: boolean
        default: false

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Update Specifications
        if: ${{ inputs.update_specs == 'true' }}
        run: |
          mkdir -p StellarOpenRPC
          mkdir -p StellarXDR
          curl -L https://raw.githubusercontent.com/stellar/stellar-rpc/main/docs/specs/stellar-rpc.openrpc.json -o StellarOpenRPC/stellar-rpc.openrpc.json
          git clone https://github.com/stellar/stellar-core.git temp-stellar-core
          cp temp-stellar-core/src/protocol-curr/*.x StellarXDR/
          rm -rf temp-stellar-core

      - name: Clean Generated Directories
        run: |
            rm -rf StellarRPCSDK/Stellar/Generated/*
            rm -rf StellarRPCSDK/RPC/Generated/*
            mkdir -p StellarRPCSDK/Stellar/Generated
            mkdir -p StellarRPCSDK/RPC/Generated

      - name: Generate SDK Code
        run: |
          ROOT_DIR=$(pwd)
          dotnet run --project Generator/Generator.csproj -- "$ROOT_DIR/StellarXDR" "$ROOT_DIR/StellarOpenRPC/stellar-rpc.openrpc.json" "$ROOT_DIR/StellarRPCSDK/Stellar/Generated" "$ROOT_DIR/StellarRPCSDK/RPC/Generated"

      - name: Build SDK Variants
        run: |
          dotnet build StellarRPCSDK/StellarRPCSDK.csproj -c Release -p:Version=${{ inputs.version }}
          dotnet build StellarRPCSDK/StellarRPCSDK.csproj -c Unity -p:Version=${{ inputs.version }}
          dotnet build StellarRPCSDK/StellarRPCSDK.csproj -c Tizen -p:Version=${{ inputs.version }}
          dotnet build StellarRPCSDK/StellarRPCSDK.csproj -c NativeAOT -p:Version=${{ inputs.version }}

      - name: Generate Protocol Buffer Wrappers
        run: |
          GRPC_OUTPUT_DIR="$(pwd)/StellarRPCSDK_Native/gRPC"
          mkdir -p "$GRPC_OUTPUT_DIR"
          dotnet run --project ProtoGenerator/ProtoGenerator.csproj -- --proto "$(pwd)/StellarRPCSDK_Native" --grpc-aot "$GRPC_OUTPUT_DIR"

      - name: Create NuGet Packages
        run: |
          mkdir -p Releases/NuGet
          # Create NuGet packages for Standard and Tizen (not Unity)
          dotnet pack StellarRPCSDK/StellarRPCSDK.csproj -c Release -p:PackageVersion=${{ inputs.version }} -o Releases/NuGet
          dotnet pack StellarRPCSDK/StellarRPCSDK.csproj -c Tizen -p:PackageVersion=${{ inputs.version }} -o Releases/NuGet

      - name: Prepare Unity Build Output
        run: |
          mkdir -p Releases/Unity
          cp StellarRPCSDK/bin/Unity/netstandard2.1/StellarRPCSDK.dll Releases/Unity/
          cp StellarRPCSDK/bin/Unity/netstandard2.1/StellarRPCSDK.pdb Releases/Unity/
          # Copy any additional required files for Unity
          # cp StellarRPCSDK/bin/Unity/netstandard2.1/StellarRPCSDK.xml Releases/Unity/  # If you have XML documentation

      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: Releases/NuGet

      - name: Upload Unity Build
        uses: actions/upload-artifact@v4
        with:
          name: unity-build
          path: Releases/Unity

      # Prepare archive with only the necessary files
      - name: Prepare Archive Files
        run: |
          mkdir -p archive_content
          cp -r StellarRPCSDK archive_content/
          cp -r StellarRPCSDK_Native archive_content/
          cp -r ProtoGenerator archive_content/
          cp -r StellarOpenRPC archive_content/
          cp -r StellarXDR archive_content/

      # Create a complete build archive with only the necessary content
      - name: Create Build Archive
        run: |
          cd archive_content
          tar -czf ../build-archive.tar.gz .
          cd ..
          ls -la

      - name: Upload Build Archive
        uses: actions/upload-artifact@v4
        with:
          name: build-archive
          path: build-archive.tar.gz

  publish_native_windows:
    needs: build
    strategy:
      matrix:
        platform: [win-x64, win-arm64]
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Create a directory to extract to
      - name: Create Extract Directory
        run: mkdir extract_dir

      # Download the build archive
      - name: Download Build Archive
        uses: actions/download-artifact@v4
        with:
          name: build-archive
          path: .

      # Extract the archive
      - name: Extract Build Archive
        shell: pwsh
        run: |
          tar -xzf build-archive.tar.gz -C extract_dir
          dir extract_dir
          dir extract_dir\StellarRPCSDK
          dir extract_dir\StellarRPCSDK_Native

      - name: Publish Native Binary
        shell: pwsh
        run: |
          mkdir -p Releases/Binaries/${{ matrix.platform }}
          dotnet publish extract_dir/StellarRPCSDK_Native/StellarRPCSDK_Native.csproj -c Release -r ${{ matrix.platform }} --self-contained -p:Version=${{ github.event.inputs.version }} -o Releases/Binaries/${{ matrix.platform }}

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: native-binary-${{ matrix.platform }}
          path: Releases/Binaries/${{ matrix.platform }}

  publish_native_linux_x64:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Create a directory to extract to
      - name: Create Extract Directory
        run: mkdir extract_dir

      # Download the build archive
      - name: Download Build Archive
        uses: actions/download-artifact@v4
        with:
          name: build-archive
          path: .

      # Extract the archive
      - name: Extract Build Archive
        run: |
          tar -xzf build-archive.tar.gz -C extract_dir
          ls -la extract_dir
          ls -la extract_dir/StellarRPCSDK
          ls -la extract_dir/StellarRPCSDK_Native

      - name: Publish Native Binary
        run: |
          mkdir -p Releases/Binaries/linux-x64
          dotnet publish extract_dir/StellarRPCSDK_Native/StellarRPCSDK_Native.csproj \
            -c Release \
            -r linux-x64 \
            --self-contained \
            -p:Version=${{ github.event.inputs.version }} \
            -o Releases/Binaries/linux-x64

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: native-binary-linux-x64
          path: Releases/Binaries/linux-x64

  publish_native_linux_arm64:
    needs: build
    # Use the GitHub-hosted ARM64 runner
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Create a directory to extract to
      - name: Create Extract Directory
        run: mkdir extract_dir

      # Download the build archive
      - name: Download Build Archive
        uses: actions/download-artifact@v4
        with:
          name: build-archive
          path: .

      # Extract the archive
      - name: Extract Build Archive
        run: |
          tar -xzf build-archive.tar.gz -C extract_dir
          ls -la extract_dir
          ls -la extract_dir/StellarRPCSDK
          ls -la extract_dir/StellarRPCSDK_Native

      - name: Publish Native Binary
        run: |
          mkdir -p Releases/Binaries/linux-arm64
          dotnet publish extract_dir/StellarRPCSDK_Native/StellarRPCSDK_Native.csproj \
            -c Release \
            -r linux-arm64 \
            --self-contained \
            -p:Version=${{ github.event.inputs.version }} \
            -o Releases/Binaries/linux-arm64

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: native-binary-linux-arm64
          path: Releases/Binaries/linux-arm64

  publish_native_macos_x64:
    needs: build
    runs-on: macos-13
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Create a directory to extract to
      - name: Create Extract Directory
        run: mkdir extract_dir

      # Download the build archive
      - name: Download Build Archive
        uses: actions/download-artifact@v4
        with:
          name: build-archive
          path: .

      # Extract the archive
      - name: Extract Build Archive
        run: |
          tar -xzf build-archive.tar.gz -C extract_dir
          ls -la extract_dir
          ls -la extract_dir/StellarRPCSDK
          ls -la extract_dir/StellarRPCSDK_Native

      - name: Publish Native Binary
        run: |
          mkdir -p Releases/Binaries/osx-x64
          dotnet publish extract_dir/StellarRPCSDK_Native/StellarRPCSDK_Native.csproj \
            -c Release \
            -r osx-x64 \
            --self-contained \
            -p:Version=${{ github.event.inputs.version }} \
            -o Releases/Binaries/osx-x64

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: native-binary-osx-x64
          path: Releases/Binaries/osx-x64

  publish_native_macos_arm64:
    needs: build
    # macOS ARM64 can be built on Intel macOS
    runs-on: macos-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Create a directory to extract to
      - name: Create Extract Directory
        run: mkdir extract_dir

      # Download the build archive
      - name: Download Build Archive
        uses: actions/download-artifact@v4
        with:
          name: build-archive
          path: .

      # Extract the archive
      - name: Extract Build Archive
        run: |
          tar -xzf build-archive.tar.gz -C extract_dir
          ls -la extract_dir
          ls -la extract_dir/StellarRPCSDK
          ls -la extract_dir/StellarRPCSDK_Native

      - name: Publish Native Binary
        run: |
          mkdir -p Releases/Binaries/osx-arm64
          dotnet publish extract_dir/StellarRPCSDK_Native/StellarRPCSDK_Native.csproj \
            -c Release \
            -r osx-arm64 \
            --self-contained \
            -p:Version=${{ github.event.inputs.version }} \
            -o Releases/Binaries/osx-arm64

      - name: Upload Native Binary
        uses: actions/upload-artifact@v4
        with:
          name: native-binary-osx-arm64
          path: Releases/Binaries/osx-arm64

  release:
    needs: [build, publish_native_windows, publish_native_linux_x64, publish_native_linux_arm64, publish_native_macos_x64, publish_native_macos_arm64]
    runs-on: ubuntu-latest
    steps:
      # Check out the repository first for git context
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # List artifact files for debugging
      - name: List artifact files
        run: |
          find artifacts -type f | sort

      # Prepare release files in a clean directory structure
      - name: Prepare release files
        run: |
          mkdir -p release_files
          # Copy the specific files we know exist
          cp artifacts/nuget-packages/*.nupkg release_files/
          cp artifacts/unity-build/*.dll release_files/
          cp artifacts/unity-build/*.pdb release_files/
          mkdir -p release_files/win-x64
          cp artifacts/native-binary-win-x64/*.dll release_files/win-x64/
          cp artifacts/native-binary-win-x64/*.pdb release_files/win-x64/
          mkdir -p release_files/win-arm64
          cp artifacts/native-binary-win-arm64/*.dll release_files/win-arm64/
          cp artifacts/native-binary-win-arm64/*.pdb release_files/win-arm64/
          mkdir -p release_files/linux-x64
          cp artifacts/native-binary-linux-x64/*.so release_files/linux-x64/
          cp artifacts/native-binary-linux-x64/*.pdb release_files/linux-x64/
          mkdir -p release_files/linux-arm64
          cp artifacts/native-binary-linux-arm64/*.so release_files/linux-arm64/
          cp artifacts/native-binary-linux-arm64/*.pdb release_files/linux-arm64/
          mkdir -p release_files/osx-x64
          cp artifacts/native-binary-osx-x64/*.dylib release_files/osx-x64/
          cp artifacts/native-binary-osx-x64/*.pdb release_files/osx-x64/
          mkdir -p release_files/osx-arm64
          cp artifacts/native-binary-osx-arm64/*.dylib release_files/osx-arm64/
          cp artifacts/native-binary-osx-arm64/*.pdb release_files/osx-arm64/
          
          # Create a zip archive of all release files
          zip -r release-v${{ github.event.inputs.version }}.zip release_files

      # Try deleting any existing release, ignoring errors
      - name: Try deleting existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete v${{ github.event.inputs.version }} --yes || true

      # Create a fresh release
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a fresh release with just the zip file
          gh release create v${{ github.event.inputs.version }} \
            --title "Release v${{ github.event.inputs.version }}" \
            --draft \
            release-v${{ github.event.inputs.version }}.zip

      # - name: Publish NuGet Packages
      #   run: |
      #     for package in artifacts/nuget-packages/*.nupkg; do
      #       dotnet nuget push $package --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      #     done

     